// Generated by scripts/generate-owned-experiment-registries.mjs. Do not edit.

export interface HighMathCurriculumPoint {
  id: string
  title: string
}

export interface HighMathCurriculumModule {
  id: string
  title: string
  points: readonly HighMathCurriculumPoint[]
}

export const HIGH_MATH_COURSE_META = {
  "id": "higher-mathematics",
  "title": "高等数学",
  "subtitle": "从函数与极限到无穷级数"
} as const

export const HIGH_MATH_CURRICULUM = [
  {
    "id": "hm-01",
    "title": "函数与基本图像",
    "points": [
      {
        "id": "hm-01-01",
        "title": "函数的定义域和值域"
      },
      {
        "id": "hm-01-02",
        "title": "函数图像"
      },
      {
        "id": "hm-01-03",
        "title": "函数的单调性"
      },
      {
        "id": "hm-01-04",
        "title": "函数的奇偶性"
      },
      {
        "id": "hm-01-05",
        "title": "函数的周期性"
      },
      {
        "id": "hm-01-06",
        "title": "反函数"
      },
      {
        "id": "hm-01-07",
        "title": "复合函数"
      },
      {
        "id": "hm-01-08",
        "title": "分段函数"
      },
      {
        "id": "hm-01-09",
        "title": "参数方程"
      },
      {
        "id": "hm-01-10",
        "title": "极坐标方程"
      },
      {
        "id": "hm-01-11",
        "title": "基本初等函数"
      },
      {
        "id": "hm-01-12",
        "title": "函数图像的平移"
      },
      {
        "id": "hm-01-13",
        "title": "函数图像的伸缩"
      },
      {
        "id": "hm-01-14",
        "title": "函数图像的翻折"
      },
      {
        "id": "hm-01-15",
        "title": "参数变化对函数图像的影响"
      }
    ]
  },
  {
    "id": "hm-02",
    "title": "数列极限与函数极限",
    "points": [
      {
        "id": "hm-02-01",
        "title": "数列趋近过程"
      },
      {
        "id": "hm-02-02",
        "title": "函数在某一点的极限"
      },
      {
        "id": "hm-02-03",
        "title": "函数在无穷远处的极限"
      },
      {
        "id": "hm-02-04",
        "title": "左极限与右极限"
      },
      {
        "id": "hm-02-05",
        "title": "无穷小与无穷大"
      },
      {
        "id": "hm-02-06",
        "title": "极限的局部性质"
      },
      {
        "id": "hm-02-07",
        "title": "极限的四则运算"
      },
      {
        "id": "hm-02-08",
        "title": "两个重要极限"
      },
      {
        "id": "hm-02-09",
        "title": "等价无穷小"
      },
      {
        "id": "hm-02-10",
        "title": "夹逼准则"
      },
      {
        "id": "hm-02-11",
        "title": "单调有界准则"
      }
    ]
  },
  {
    "id": "hm-03",
    "title": "连续与间断",
    "points": [
      {
        "id": "hm-03-01",
        "title": "函数在一点连续"
      },
      {
        "id": "hm-03-02",
        "title": "左连续与右连续"
      },
      {
        "id": "hm-03-03",
        "title": "区间连续"
      },
      {
        "id": "hm-03-04",
        "title": "可去间断点"
      },
      {
        "id": "hm-03-05",
        "title": "跳跃间断点"
      },
      {
        "id": "hm-03-06",
        "title": "无穷间断点"
      },
      {
        "id": "hm-03-07",
        "title": "振荡间断点"
      },
      {
        "id": "hm-03-08",
        "title": "连续函数的性质"
      },
      {
        "id": "hm-03-09",
        "title": "零点定理"
      },
      {
        "id": "hm-03-10",
        "title": "介值定理"
      },
      {
        "id": "hm-03-11",
        "title": "最大值与最小值定理"
      }
    ]
  },
  {
    "id": "hm-04",
    "title": "导数与微分",
    "points": [
      {
        "id": "hm-04-01",
        "title": "导数的定义"
      },
      {
        "id": "hm-04-02",
        "title": "割线与切线"
      },
      {
        "id": "hm-04-03",
        "title": "左导数与右导数"
      },
      {
        "id": "hm-04-04",
        "title": "函数的可导性"
      },
      {
        "id": "hm-04-05",
        "title": "导数的几何意义"
      },
      {
        "id": "hm-04-06",
        "title": "导数的物理意义"
      },
      {
        "id": "hm-04-07",
        "title": "基本求导公式"
      },
      {
        "id": "hm-04-08",
        "title": "复合函数求导"
      },
      {
        "id": "hm-04-09",
        "title": "隐函数求导"
      },
      {
        "id": "hm-04-10",
        "title": "参数方程求导"
      },
      {
        "id": "hm-04-11",
        "title": "高阶导数"
      },
      {
        "id": "hm-04-12",
        "title": "微分的定义"
      },
      {
        "id": "hm-04-13",
        "title": "局部线性化"
      },
      {
        "id": "hm-04-14",
        "title": "微分近似"
      }
    ]
  },
  {
    "id": "hm-05",
    "title": "微分中值定理与导数应用",
    "points": [
      {
        "id": "hm-05-01",
        "title": "罗尔定理"
      },
      {
        "id": "hm-05-02",
        "title": "拉格朗日中值定理"
      },
      {
        "id": "hm-05-03",
        "title": "柯西中值定理"
      },
      {
        "id": "hm-05-04",
        "title": "洛必达法则"
      },
      {
        "id": "hm-05-05",
        "title": "函数单调性"
      },
      {
        "id": "hm-05-06",
        "title": "极值"
      },
      {
        "id": "hm-05-07",
        "title": "最大值与最小值"
      },
      {
        "id": "hm-05-08",
        "title": "凹凸性"
      },
      {
        "id": "hm-05-09",
        "title": "拐点"
      },
      {
        "id": "hm-05-10",
        "title": "渐近线"
      },
      {
        "id": "hm-05-11",
        "title": "函数图像描绘"
      },
      {
        "id": "hm-05-12",
        "title": "曲率"
      },
      {
        "id": "hm-05-13",
        "title": "曲率圆"
      },
      {
        "id": "hm-05-14",
        "title": "最优化问题"
      }
    ]
  },
  {
    "id": "hm-06",
    "title": "不定积分",
    "points": [
      {
        "id": "hm-06-01",
        "title": "原函数"
      },
      {
        "id": "hm-06-02",
        "title": "不定积分"
      },
      {
        "id": "hm-06-03",
        "title": "基本积分公式"
      },
      {
        "id": "hm-06-04",
        "title": "换元积分法"
      },
      {
        "id": "hm-06-05",
        "title": "分部积分法"
      },
      {
        "id": "hm-06-06",
        "title": "有理函数积分"
      },
      {
        "id": "hm-06-07",
        "title": "三角函数积分"
      },
      {
        "id": "hm-06-08",
        "title": "三角换元"
      }
    ]
  },
  {
    "id": "hm-07",
    "title": "定积分",
    "points": [
      {
        "id": "hm-07-01",
        "title": "定积分定义"
      },
      {
        "id": "hm-07-02",
        "title": "黎曼和"
      },
      {
        "id": "hm-07-03",
        "title": "可积性"
      },
      {
        "id": "hm-07-04",
        "title": "定积分性质"
      },
      {
        "id": "hm-07-05",
        "title": "积分中值定理"
      },
      {
        "id": "hm-07-06",
        "title": "微积分基本公式"
      },
      {
        "id": "hm-07-07",
        "title": "牛顿—莱布尼茨公式"
      },
      {
        "id": "hm-07-08",
        "title": "定积分换元法"
      },
      {
        "id": "hm-07-09",
        "title": "定积分分部积分法"
      },
      {
        "id": "hm-07-10",
        "title": "反常积分"
      }
    ]
  },
  {
    "id": "hm-08",
    "title": "定积分的应用",
    "points": [
      {
        "id": "hm-08-01",
        "title": "平面图形面积"
      },
      {
        "id": "hm-08-02",
        "title": "极坐标面积"
      },
      {
        "id": "hm-08-03",
        "title": "旋转体体积"
      },
      {
        "id": "hm-08-04",
        "title": "平行截面面积已知的立体体积"
      },
      {
        "id": "hm-08-05",
        "title": "平面曲线弧长"
      },
      {
        "id": "hm-08-06",
        "title": "功"
      },
      {
        "id": "hm-08-07",
        "title": "水压力"
      },
      {
        "id": "hm-08-08",
        "title": "引力"
      },
      {
        "id": "hm-08-09",
        "title": "函数平均值"
      }
    ]
  },
  {
    "id": "hm-09",
    "title": "微分方程",
    "points": [
      {
        "id": "hm-09-01",
        "title": "微分方程基本概念"
      },
      {
        "id": "hm-09-02",
        "title": "可分离变量微分方程"
      },
      {
        "id": "hm-09-03",
        "title": "齐次微分方程"
      },
      {
        "id": "hm-09-04",
        "title": "一阶线性微分方程"
      },
      {
        "id": "hm-09-05",
        "title": "伯努利方程"
      },
      {
        "id": "hm-09-06",
        "title": "可降阶高阶微分方程"
      },
      {
        "id": "hm-09-07",
        "title": "二阶常系数线性微分方程"
      },
      {
        "id": "hm-09-08",
        "title": "方程通解与特解"
      },
      {
        "id": "hm-09-09",
        "title": "初值问题"
      },
      {
        "id": "hm-09-10",
        "title": "微分方程实际应用模型"
      }
    ]
  },
  {
    "id": "hm-10",
    "title": "空间解析几何与向量代数",
    "points": [
      {
        "id": "hm-10-01",
        "title": "空间直角坐标系"
      },
      {
        "id": "hm-10-02",
        "title": "向量及其运算"
      },
      {
        "id": "hm-10-03",
        "title": "数量积"
      },
      {
        "id": "hm-10-04",
        "title": "向量积"
      },
      {
        "id": "hm-10-05",
        "title": "混合积"
      },
      {
        "id": "hm-10-06",
        "title": "平面方程"
      },
      {
        "id": "hm-10-07",
        "title": "空间直线方程"
      },
      {
        "id": "hm-10-08",
        "title": "直线与平面的位置关系"
      },
      {
        "id": "hm-10-09",
        "title": "曲面方程"
      },
      {
        "id": "hm-10-10",
        "title": "空间曲线"
      },
      {
        "id": "hm-10-11",
        "title": "二次曲面"
      }
    ]
  },
  {
    "id": "hm-11",
    "title": "多元函数微分学",
    "points": [
      {
        "id": "hm-11-01",
        "title": "多元函数"
      },
      {
        "id": "hm-11-02",
        "title": "二元函数的极限"
      },
      {
        "id": "hm-11-03",
        "title": "二元函数的连续性"
      },
      {
        "id": "hm-11-04",
        "title": "偏导数"
      },
      {
        "id": "hm-11-05",
        "title": "全微分"
      },
      {
        "id": "hm-11-06",
        "title": "多元复合函数求导"
      },
      {
        "id": "hm-11-07",
        "title": "多元隐函数求导"
      },
      {
        "id": "hm-11-08",
        "title": "方向导数"
      },
      {
        "id": "hm-11-09",
        "title": "梯度"
      },
      {
        "id": "hm-11-10",
        "title": "多元函数极值"
      },
      {
        "id": "hm-11-11",
        "title": "条件极值"
      },
      {
        "id": "hm-11-12",
        "title": "拉格朗日乘数法"
      }
    ]
  },
  {
    "id": "hm-12",
    "title": "重积分",
    "points": [
      {
        "id": "hm-12-01",
        "title": "二重积分定义"
      },
      {
        "id": "hm-12-02",
        "title": "直角坐标下的二重积分"
      },
      {
        "id": "hm-12-03",
        "title": "极坐标下的二重积分"
      },
      {
        "id": "hm-12-04",
        "title": "三重积分"
      },
      {
        "id": "hm-12-05",
        "title": "柱面坐标"
      },
      {
        "id": "hm-12-06",
        "title": "球面坐标"
      },
      {
        "id": "hm-12-07",
        "title": "重积分应用"
      }
    ]
  },
  {
    "id": "hm-13",
    "title": "曲线积分与曲面积分",
    "points": [
      {
        "id": "hm-13-01",
        "title": "第一类曲线积分"
      },
      {
        "id": "hm-13-02",
        "title": "第二类曲线积分"
      },
      {
        "id": "hm-13-03",
        "title": "第一类曲面积分"
      },
      {
        "id": "hm-13-04",
        "title": "第二类曲面积分"
      },
      {
        "id": "hm-13-05",
        "title": "格林公式"
      },
      {
        "id": "hm-13-06",
        "title": "高斯公式"
      },
      {
        "id": "hm-13-07",
        "title": "斯托克斯公式"
      },
      {
        "id": "hm-13-08",
        "title": "曲线积分与路径无关"
      },
      {
        "id": "hm-13-09",
        "title": "保守场与势函数"
      }
    ]
  },
  {
    "id": "hm-14",
    "title": "无穷级数",
    "points": [
      {
        "id": "hm-14-01",
        "title": "常数项级数"
      },
      {
        "id": "hm-14-02",
        "title": "正项级数"
      },
      {
        "id": "hm-14-03",
        "title": "交错级数"
      },
      {
        "id": "hm-14-04",
        "title": "绝对收敛与条件收敛"
      },
      {
        "id": "hm-14-05",
        "title": "幂级数"
      },
      {
        "id": "hm-14-06",
        "title": "收敛半径"
      },
      {
        "id": "hm-14-07",
        "title": "函数展开成幂级数"
      },
      {
        "id": "hm-14-08",
        "title": "泰勒级数"
      },
      {
        "id": "hm-14-09",
        "title": "傅里叶级数"
      }
    ]
  }
] as const satisfies readonly HighMathCurriculumModule[]
